[tool.pylint.main]
py-version = "3.8"

[tool.pylint."messages control"]
disable = """W,R,C,
    no-self-argument,
    undefined-variable,
    no-name-in-module,
    no-member,
    invalid-unary-operand-type,
    function-redefined,
    not-callable,
    unsupported-binary-operation,
"""
# see https://pylint.readthedocs.io/en/latest/user_guide/messages/messages_overview.html
# for a list of all messages
enable = [
    "unnecessary-pass",
]
