name: Feature Request 💡
description: Suggest a new feature
labels: enhancement

body:

  - type: textarea
    attributes:
      label: Description
      description: Explanation of the feature.

  - type: textarea
    attributes:
      label: Motivation
      description: Why should we do this?

  - type: textarea
    attributes:
      label: Possible Implementation
      description: Suggest an idea for implementing the addition or change.

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
